version: "3.1"

services:

  db:
    container_name: demo2_db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=t3kit
      - MYSQL_USER=t3kit
      - MYSQL_PASSWORD=t3kit1234
    restart: always
    ports:
      - "3307:3306"
  web:
    container_name: demo2_web
    image: t3kit/ubuntu16-php7-apache:0.0.1
    ports:
      - "8888:80"
    depends_on:
      - db
      - t3kit_solr
    volumes:
      - ./docker_conf:/docker_conf
      - ./vendor/t3kit/db:/t3kit_db
      - t3kit-sync:/var/www/html:rw
    restart: always
    command: "sh /docker_conf/macos/run.sh"
    environment:
      - USERID=501
      - GROUPID=20

  t3kit_solr:
    container_name: demo2_t3kit_solr
    image: typo3solr/ext-solr:6.0.0
    ports:
      - "8983:8983"
    volumes:
      - ./solrdata:/opt/solr/server/solr/data/
    restart: always
  mailhog:
    container_name: demo2_t3kit_mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  t3kit-sync:
    external: true
